"""Checklist REST API endpoints.

GET /api/v1/checklists/today       — today's checklist for the authenticated contractor
GET /api/v1/checklists/{id}        — single checklist by ID

Both endpoints require authentication. The checklist data is generated by the morning
cron job (06:00 UTC) and stored in daily_checklists. These endpoints are read-only.
"""

from __future__ import annotations

import uuid
from datetime import date

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.security import CurrentUser, get_current_user
from app.features.checklists.schemas import ChecklistResponse
from app.features.checklists.service import ChecklistService

router = APIRouter(prefix="/checklists", tags=["checklists"])


@router.get("/today", response_model=list[ChecklistResponse])
async def get_today_checklist(
    db: AsyncSession = Depends(get_db),
    current_user: CurrentUser = Depends(get_current_user),
) -> list[ChecklistResponse]:
    """Return today's AI-generated checklist(s) for the authenticated contractor.

    Returns a list because a contractor can have multiple trade scopes on the same date.
    Returns an empty list (200) if no checklist has been generated yet for today.
    """
    svc = ChecklistService(db)
    checklists = await svc.get_today_checklist(
        contractor_id=current_user.user_id,
        target_date=date.today(),
    )
    return [ChecklistResponse.model_validate(c) for c in checklists]


@router.get("/{checklist_id}", response_model=ChecklistResponse)
async def get_checklist(
    checklist_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: CurrentUser = Depends(get_current_user),
) -> ChecklistResponse:
    """Return a specific checklist by ID.

    Returns 404 if not found or if the checklist belongs to a different tenant
    (RLS enforces tenant isolation automatically).
    """
    svc = ChecklistService(db)
    checklist = await svc.get_checklist_by_id(checklist_id)
    if checklist is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Checklist not found",
        )
    return ChecklistResponse.model_validate(checklist)
