"""Pydantic schemas for daily checklist API responses."""

from __future__ import annotations

import uuid
from datetime import date

from pydantic import BaseModel

from app.core.base_schemas import TenantResponseSchema


class ChecklistItemSchema(BaseModel):
    """Single task item within a checklist JSON payload.

    Matches the JSON schema generated by CHECKLIST_SYSTEM_PROMPT:
    - task_id: UUID of the Task record this checklist item refers to
    - title: task display name
    - priority: 1 = highest priority (to do first today)
    - materials_needed: list of material/tool names needed
    - photo_required: whether a completion photo must be attached
    - estimated_minutes: AI-estimated time to complete
    - notes: any AI-generated notes or context for this task
    - dependency_status: 'clear' | 'blocked' | 'waiting' for the contractor to understand blockers
    """

    # Issue-7: Use str instead of uuid.UUID — AI may generate non-UUID identifiers
    task_id: str
    title: str
    priority: int = 1
    materials_needed: list[str] = []
    photo_required: bool = False
    estimated_minutes: int = 60
    notes: str = ""
    dependency_status: str = "clear"


class ChecklistPayload(BaseModel):
    """BP-7: Validated structure for checklist_json instead of untyped dict.

    The AI generates a JSON object with a 'tasks' list matching ChecklistItemSchema.
    """

    tasks: list[ChecklistItemSchema] = []


class ChecklistResponse(TenantResponseSchema):
    """Full daily checklist response including all tasks for the contractor today."""

    contractor_id: uuid.UUID
    project_id: uuid.UUID
    trade_scope_id: uuid.UUID
    checklist_date: date
    # Issue-7: Use plain dict for safe passthrough — AI responses may not match strict schema
    checklist_json: dict
    summary_text: str
    is_pushed: bool
