import 'package:flutter/foundation.dart';

/// A message in an AI chat conversation.
@immutable
class ChatMessage {
  const ChatMessage({
    required this.id,
    required this.role,
    required this.text,
    this.imageUrl,
    this.timestamp,
  });

  /// Unique message identifier
  final String id;

  /// 'user' | 'assistant'
  final String role;

  /// Message text content
  final String text;

  /// Optional image attachment URL
  final String? imageUrl;

  final DateTime? timestamp;

  bool get isUser => role == 'user';
  bool get isAssistant => role == 'assistant';

  ChatMessage copyWith({String? text}) {
    return ChatMessage(
      id: id,
      role: role,
      text: text ?? this.text,
      imageUrl: imageUrl,
      timestamp: timestamp,
    );
  }
}

/// A trade scope generated by the AI intake conversation.
@immutable
class AiTradeScope {
  const AiTradeScope({
    required this.id,
    required this.tradeName,
    required this.tradeType,
    this.tradeColor = '#3949AB',
    this.description,
    this.sortOrder = 0,
    this.estimatedDays,
  });

  factory AiTradeScope.fromJson(Map<String, dynamic> json) {
    return AiTradeScope(
      id: json['id'] as String? ?? '',
      tradeName: json['trade_name'] as String? ?? '',
      tradeType: json['trade_type'] as String? ?? '',
      tradeColor: json['trade_color'] as String? ?? '#3949AB',
      description: json['description'] as String?,
      sortOrder: (json['sort_order'] as num?)?.toInt() ?? 0,
      estimatedDays: (json['estimated_days'] as num?)?.toInt(),
    );
  }

  final String id;
  final String tradeName;
  final String tradeType;
  final String tradeColor;
  final String? description;
  final int sortOrder;
  final int? estimatedDays;

  Map<String, dynamic> toJson() => {
        'id': id,
        'trade_name': tradeName,
        'trade_type': tradeType,
        'trade_color': tradeColor,
        'description': description,
        'sort_order': sortOrder,
        'estimated_days': estimatedDays,
      };
}

/// A task generated by the AI interview conversation.
@immutable
class AiTaskPreview {
  const AiTaskPreview({
    required this.id,
    required this.title,
    this.description,
    this.priority = 'medium',
    this.estimatedHours,
    this.materials = const [],
    this.sortOrder = 0,
  });

  factory AiTaskPreview.fromJson(Map<String, dynamic> json) {
    final materialsList = json['materials'];
    List<String> materials = [];
    if (materialsList is List) {
      materials = materialsList.whereType<String>().toList();
    }

    return AiTaskPreview(
      id: json['id'] as String? ?? '',
      title: json['title'] as String? ?? '',
      description: json['description'] as String?,
      priority: json['priority'] as String? ?? 'medium',
      estimatedHours: (json['estimated_hours'] as num?)?.toDouble(),
      materials: materials,
      sortOrder: (json['sort_order'] as num?)?.toInt() ?? 0,
    );
  }

  final String id;
  final String title;
  final String? description;
  final String priority;
  final double? estimatedHours;
  final List<String> materials;
  final int sortOrder;

  AiTaskPreview copyWith({
    String? title,
    String? description,
    String? priority,
    double? estimatedHours,
    List<String>? materials,
    int? sortOrder,
  }) {
    return AiTaskPreview(
      id: id,
      title: title ?? this.title,
      description: description ?? this.description,
      priority: priority ?? this.priority,
      estimatedHours: estimatedHours ?? this.estimatedHours,
      materials: materials ?? this.materials,
      sortOrder: sortOrder ?? this.sortOrder,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'title': title,
        'description': description,
        'priority': priority,
        'estimated_hours': estimatedHours,
        'materials': materials,
        'sort_order': sortOrder,
      };
}
