import 'dart:convert';

import 'package:drift/drift.dart' as drift;
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:get_it/get_it.dart';
import 'package:uuid/uuid.dart';

import '../../../../core/database/app_database.dart';
import '../../data/ai_conversation_dao.dart';
import '../../data/ai_sse_client.dart';
import '../../domain/ai_models.dart';

/// State for the GC AI intake chat session.
@immutable
class IntakeChatState {
  const IntakeChatState({
    this.messages = const [],
    this.isStreaming = false,
    this.currentStreamText = '',
    this.tradeScopes = const [],
    this.conversationId,
    this.error,
  });

  /// Chat message history (user + assistant turns)
  final List<ChatMessage> messages;

  /// True while the SSE stream is actively delivering tokens
  final bool isStreaming;

  /// Accumulated text of the current assistant turn (before finalized)
  final String currentStreamText;

  /// Trade scopes generated by AI tool calls during intake
  final List<AiTradeScope> tradeScopes;

  /// Backend conversation ID (null until startConversation completes)
  final String? conversationId;

  /// Error message if the last operation failed
  final String? error;

  IntakeChatState copyWith({
    List<ChatMessage>? messages,
    bool? isStreaming,
    String? currentStreamText,
    List<AiTradeScope>? tradeScopes,
    String? conversationId,
    String? error,
  }) {
    return IntakeChatState(
      messages: messages ?? this.messages,
      isStreaming: isStreaming ?? this.isStreaming,
      currentStreamText: currentStreamText ?? this.currentStreamText,
      tradeScopes: tradeScopes ?? this.tradeScopes,
      conversationId: conversationId ?? this.conversationId,
      error: error,
    );
  }
}

/// Riverpod notifier for the GC AI intake chat flow.
///
/// NOTE: GetIt is used inside this notifier (not as a Riverpod provider) because
/// AiSseClient and AiConversationDao are registered in GetIt as singletons that
/// require the AppDatabase instance. Mixing GetIt here is intentional and documented
/// per CLAUDE.md: "Do NOT mix GetIt service locator calls inside Riverpod providers
/// without documenting the tradeoff." Tradeoff: simplicity over pure DI.
///
/// NOTE: Sync Notifier (not AsyncNotifier) is used because build() is synchronous —
/// the initial state is empty and all async operations happen in methods.
/// CLAUDE.md: "If using sync Notifier with fire-and-forget async, document why explicitly."
class IntakeChatNotifier extends Notifier<IntakeChatState> {
  static const _uuid = Uuid();

  AiSseClient get _sseClient => GetIt.instance<AiSseClient>();
  AiConversationDao get _conversationDao => GetIt.instance<AiConversationDao>();

  @override
  IntakeChatState build() => const IntakeChatState();

  /// Start a new intake conversation.
  ///
  /// Posts to /api/v1/ai/intake/start. On success, stores the conversationId.
  /// If [projectId] is provided, resumes/extends an existing project's intake.
  Future<void> startConversation(String? projectId) async {
    try {
      final body = <String, dynamic>{};
      if (projectId != null) body['project_id'] = projectId;

      final response = await _sseClient.post(
        '/api/v1/ai/intake/start',
        body,
      );

      final convId = response['id'] as String?;
      if (convId == null) {
        throw FormatException('Missing id in intake/start response');
      }

      state = state.copyWith(conversationId: convId, error: null);
    } catch (e) {
      debugPrint('[IntakeChatNotifier] startConversation error: $e');
      state = state.copyWith(
        error: 'Failed to start conversation. Please check your connection.',
      );
    }
  }

  /// Send a user message and stream the AI response.
  ///
  /// Appends user message to history, then subscribes to SSE stream from
  /// /api/v1/ai/intake/message. Handles token events (text streaming),
  /// tool_call events (trade scope creation), and done/error events.
  Future<void> sendMessage(String message) async {
    final convId = state.conversationId;
    if (convId == null) {
      state = state.copyWith(error: 'No active conversation. Please restart.');
      return;
    }

    if (state.isStreaming) return;

    // Append user message to history
    final userMsg = ChatMessage(
      id: _uuid.v4(),
      role: 'user',
      text: message,
      timestamp: DateTime.now(),
    );
    state = state.copyWith(
      messages: [...state.messages, userMsg],
      isStreaming: true,
      currentStreamText: '',
      error: null,
    );

    String assistantText = '';
    final updatedScopes = List<AiTradeScope>.from(state.tradeScopes);

    try {
      final stream = _sseClient.streamChatTurn(
        path: '/api/v1/ai/intake/message',
        body: {
          'conversation_id': convId,
          'message': message,
        },
      );

      await for (final event in stream) {
        switch (event.event) {
          case 'token':
            final delta = event.dataJson['delta'] as String? ?? '';
            assistantText += delta;
            state = state.copyWith(
              currentStreamText: assistantText,
              isStreaming: true,
            );

          case 'tool_call':
            final tool = event.dataJson['tool'] as String?;
            final input = event.dataJson['input'];

            if (tool == 'create_trade_scope' && input is Map<String, dynamic>) {
              final scope = AiTradeScope.fromJson({
                'id': _uuid.v4(),
                ...input,
              });
              updatedScopes.add(scope);
              state = state.copyWith(tradeScopes: List.unmodifiable(updatedScopes));
            } else if (tool == 'ask_clarifying_question' &&
                input is Map<String, dynamic>) {
              final question = input['question'] as String? ?? '';
              if (question.isNotEmpty) {
                assistantText +=
                    assistantText.isNotEmpty ? '\n\n$question' : question;
                state = state.copyWith(currentStreamText: assistantText);
              }
            }

          case 'done':
            // Finalize the assistant message
            if (assistantText.isNotEmpty) {
              final assistantMsg = ChatMessage(
                id: _uuid.v4(),
                role: 'assistant',
                text: assistantText,
                timestamp: DateTime.now(),
              );
              state = state.copyWith(
                messages: [...state.messages, assistantMsg],
                isStreaming: false,
                currentStreamText: '',
                tradeScopes: List.unmodifiable(updatedScopes),
              );
            } else {
              state = state.copyWith(
                isStreaming: false,
                currentStreamText: '',
                tradeScopes: List.unmodifiable(updatedScopes),
              );
            }

          case 'error':
            final errorMsg = event.dataJson['message'] as String? ??
                'An error occurred during streaming.';
            debugPrint('[IntakeChatNotifier] SSE error event: $errorMsg');
            state = state.copyWith(
              isStreaming: false,
              currentStreamText: '',
              error: errorMsg,
            );
        }
      }
    } catch (e) {
      debugPrint('[IntakeChatNotifier] sendMessage error: $e');
      // Finalize partial text if any was accumulated
      if (assistantText.isNotEmpty) {
        final assistantMsg = ChatMessage(
          id: _uuid.v4(),
          role: 'assistant',
          text: assistantText,
          timestamp: DateTime.now(),
        );
        state = state.copyWith(
          messages: [...state.messages, assistantMsg],
          isStreaming: false,
          currentStreamText: '',
          error: 'Connection interrupted. Partial response shown.',
        );
      } else {
        state = state.copyWith(
          isStreaming: false,
          currentStreamText: '',
          error: 'Failed to get response. Please try again.',
        );
      }
    }
  }

  /// Complete the intake flow and create the project.
  ///
  /// Posts to /api/v1/ai/intake/complete with the final trade scope list.
  /// On success, syncs the transcript to Drift (D-31) and returns the project ID.
  Future<String?> completeIntake({
    required String projectName,
    String? description,
    required List<AiTradeScope> scopes,
  }) async {
    final convId = state.conversationId;
    if (convId == null) return null;

    try {
      final response = await _sseClient.post(
        '/api/v1/ai/intake/complete',
        {
          'conversation_id': convId,
          'project_name': projectName,
          if (description != null) 'project_description': description,
          'trade_scopes': scopes.map((s) => s.toJson()).toList(),
        },
      );

      // D-31: Sync transcript to Drift after completion
      await _syncTranscriptToLocal(convId, 'intake');

      return response['project_id'] as String?;
    } catch (e) {
      debugPrint('[IntakeChatNotifier] completeIntake error: $e');
      state = state.copyWith(error: 'Failed to create project. Please try again.');
      return null;
    }
  }

  /// Sync the conversation transcript to local Drift DB (D-31).
  ///
  /// Fetches the full conversation from the backend and stores it locally
  /// for offline viewing.
  Future<void> _syncTranscriptToLocal(
    String conversationId,
    String convType,
  ) async {
    try {
      final convData = await _sseClient.get(
        '/api/v1/ai/conversations/$conversationId',
      );

      final now = DateTime.now();
      await _conversationDao.upsertConversation(
        AiConversationsCompanion.insert(
          id: conversationId,
          companyId: convData['company_id'] as String? ?? '',
          projectId: drift.Value(convData['project_id'] as String?),
          scopeId: drift.Value(convData['scope_id'] as String?),
          userId: convData['user_id'] as String? ?? '',
          convType: convType,
          status: const drift.Value('completed'),
          transcriptJson: drift.Value(
            jsonEncode(convData['messages'] ?? []),
          ),
          createdAt: now,
          updatedAt: now,
        ),
      );
    } catch (e) {
      // Non-fatal: local sync failure doesn't fail the completion
      debugPrint('[IntakeChatNotifier] _syncTranscriptToLocal error: $e');
    }
  }
}

/// Provider for the intake chat notifier.
final intakeChatProvider =
    NotifierProvider<IntakeChatNotifier, IntakeChatState>(
  IntakeChatNotifier.new,
);
