import 'dart:convert';

import 'package:drift/drift.dart' as drift;
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:get_it/get_it.dart';
import 'package:uuid/uuid.dart';

// Hide Drift-generated ChatMessage to avoid conflict with AI domain model.
import '../../../../core/database/app_database.dart' hide ChatMessage;
import '../../data/ai_conversation_dao.dart';
import '../../data/ai_sse_client.dart';
import '../../domain/ai_models.dart';

/// State for the contractor AI interview chat session.
@immutable
class InterviewChatState {
  const InterviewChatState({
    this.messages = const [],
    this.isStreaming = false,
    this.currentStreamText = '',
    this.tasks = const [],
    this.conversationId,
    this.scopeId,
    this.tradeName,
    this.error,
  });

  /// Chat message history (user + assistant turns)
  final List<ChatMessage> messages;

  /// True while the SSE stream is actively delivering tokens
  final bool isStreaming;

  /// Accumulated text of the current assistant turn (before finalized)
  final String currentStreamText;

  /// Task previews generated by AI tool calls during the interview
  final List<AiTaskPreview> tasks;

  /// Backend conversation ID (null until startInterview completes)
  final String? conversationId;

  /// Trade scope ID this interview is for
  final String? scopeId;

  /// Display name of the trade (used in UI copy)
  final String? tradeName;

  /// Error message if the last operation failed
  final String? error;

  InterviewChatState copyWith({
    List<ChatMessage>? messages,
    bool? isStreaming,
    String? currentStreamText,
    List<AiTaskPreview>? tasks,
    String? conversationId,
    String? scopeId,
    String? tradeName,
    String? error,
  }) {
    return InterviewChatState(
      messages: messages ?? this.messages,
      isStreaming: isStreaming ?? this.isStreaming,
      currentStreamText: currentStreamText ?? this.currentStreamText,
      tasks: tasks ?? this.tasks,
      conversationId: conversationId ?? this.conversationId,
      scopeId: scopeId ?? this.scopeId,
      tradeName: tradeName ?? this.tradeName,
      error: error,
    );
  }
}

/// Riverpod notifier for the contractor AI interview chat flow.
///
/// NOTE: GetIt is used inside this notifier per CLAUDE.md guidance.
/// Tradeoff: simplicity over pure DI for GetIt-registered singletons.
///
/// NOTE: Sync Notifier (not AsyncNotifier) — build() is synchronous.
/// All async operations happen in public methods.
///
/// NOTE: Uses constructor injection of scopeId per Riverpod 3 family pattern
/// (factory (arg) => Notifier(arg) — no FamilyNotifier class exists in Riverpod 3).
class InterviewChatNotifier extends Notifier<InterviewChatState> {
  static const _uuid = Uuid();

  final String scopeId;
  InterviewChatNotifier(this.scopeId);

  AiSseClient get _sseClient => GetIt.instance<AiSseClient>();
  AiConversationDao get _conversationDao => GetIt.instance<AiConversationDao>();

  @override
  InterviewChatState build() {
    return InterviewChatState(scopeId: scopeId);
  }

  /// Start a new interview conversation for the given scope.
  ///
  /// Posts to /api/v1/ai/interview/start. On success, stores the conversationId.
  Future<void> startInterview({String? tradeName}) async {
    try {
      final response = await _sseClient.post(
        '/api/v1/ai/interview/start',
        {'scope_id': scopeId},
      );

      final convId = response['id'] as String?;
      if (convId == null) {
        throw FormatException('Missing id in interview/start response');
      }

      state = state.copyWith(
        conversationId: convId,
        tradeName: tradeName,
        error: null,
      );
    } catch (e) {
      debugPrint('[InterviewChatNotifier] startInterview error: $e');
      state = state.copyWith(
        error: 'Failed to start interview. Please check your connection.',
      );
    }
  }

  /// Send a user message and stream the AI response.
  ///
  /// Appends user message to history, then subscribes to SSE stream from
  /// /api/v1/ai/interview/message. Handles token events (text streaming),
  /// tool_call events (task creation), and done/error events.
  Future<void> sendMessage(String message) async {
    final convId = state.conversationId;
    if (convId == null) {
      state = state.copyWith(error: 'No active interview. Please restart.');
      return;
    }

    if (state.isStreaming) return;

    // Append user message to history
    final userMsg = ChatMessage(
      id: _uuid.v4(),
      role: 'user',
      text: message,
      timestamp: DateTime.now(),
    );
    state = state.copyWith(
      messages: [...state.messages, userMsg],
      isStreaming: true,
      currentStreamText: '',
      error: null,
    );

    String assistantText = '';
    final updatedTasks = List<AiTaskPreview>.from(state.tasks);

    try {
      final stream = _sseClient.streamChatTurn(
        path: '/api/v1/ai/interview/message',
        body: {
          'conversation_id': convId,
          'message': message,
        },
      );

      await for (final event in stream) {
        switch (event.event) {
          case 'token':
            final delta = event.dataJson['delta'] as String? ?? '';
            assistantText += delta;
            state = state.copyWith(
              currentStreamText: assistantText,
              isStreaming: true,
            );

          case 'tool_call':
            final tool = event.dataJson['tool'] as String?;
            final input = event.dataJson['input'];

            if (tool == 'create_task' && input is Map<String, dynamic>) {
              final task = AiTaskPreview.fromJson({
                'id': _uuid.v4(),
                ...input,
              });
              updatedTasks.add(task);
              state = state.copyWith(tasks: List.unmodifiable(updatedTasks));
            } else if (tool == 'ask_clarifying_question' &&
                input is Map<String, dynamic>) {
              final question = input['question'] as String? ?? '';
              if (question.isNotEmpty) {
                assistantText +=
                    assistantText.isNotEmpty ? '\n\n$question' : question;
                state = state.copyWith(currentStreamText: assistantText);
              }
            }

          case 'done':
            if (assistantText.isNotEmpty) {
              final assistantMsg = ChatMessage(
                id: _uuid.v4(),
                role: 'assistant',
                text: assistantText,
                timestamp: DateTime.now(),
              );
              state = state.copyWith(
                messages: [...state.messages, assistantMsg],
                isStreaming: false,
                currentStreamText: '',
                tasks: List.unmodifiable(updatedTasks),
              );
            } else {
              state = state.copyWith(
                isStreaming: false,
                currentStreamText: '',
                tasks: List.unmodifiable(updatedTasks),
              );
            }

          case 'error':
            final errorMsg = event.dataJson['message'] as String? ??
                'An error occurred during streaming.';
            debugPrint('[InterviewChatNotifier] SSE error event: $errorMsg');
            state = state.copyWith(
              isStreaming: false,
              currentStreamText: '',
              error: errorMsg,
            );
        }
      }
    } catch (e) {
      debugPrint('[InterviewChatNotifier] sendMessage error: $e');
      if (assistantText.isNotEmpty) {
        final assistantMsg = ChatMessage(
          id: _uuid.v4(),
          role: 'assistant',
          text: assistantText,
          timestamp: DateTime.now(),
        );
        state = state.copyWith(
          messages: [...state.messages, assistantMsg],
          isStreaming: false,
          currentStreamText: '',
          error: 'Connection interrupted. Partial response shown.',
        );
      } else {
        state = state.copyWith(
          isStreaming: false,
          currentStreamText: '',
          error: 'Failed to get response. Please try again.',
        );
      }
    }
  }

  /// Complete the interview and create the tasks.
  ///
  /// Posts to /api/v1/ai/interview/complete with the edited task list.
  /// On success, syncs transcript to Drift (D-31) and returns task IDs.
  Future<List<String>> completeInterview(List<AiTaskPreview> editedTasks) async {
    final convId = state.conversationId;
    if (convId == null) return [];

    try {
      final response = await _sseClient.post(
        '/api/v1/ai/interview/complete',
        {
          'conversation_id': convId,
          'tasks': editedTasks.map((t) => t.toJson()).toList(),
        },
      );

      // D-31: Sync transcript to Drift after completion
      await _syncTranscriptToLocal(convId, 'interview');

      final taskIds = response['task_ids'];
      if (taskIds is List) {
        return taskIds.whereType<String>().toList();
      }
      return [];
    } catch (e) {
      debugPrint('[InterviewChatNotifier] completeInterview error: $e');
      state = state.copyWith(error: 'Failed to save tasks. Please try again.');
      return [];
    }
  }

  /// Restart the interview from scratch.
  ///
  /// Clears all state and starts a new conversation for the same scope.
  Future<void> restartInterview({String? tradeName}) async {
    final currentTradeName = tradeName ?? state.tradeName;
    state = InterviewChatState(scopeId: scopeId, tradeName: currentTradeName);
    await startInterview(tradeName: currentTradeName);
  }

  /// Sync the conversation transcript to local Drift DB (D-31).
  Future<void> _syncTranscriptToLocal(
    String conversationId,
    String convType,
  ) async {
    try {
      final convData = await _sseClient.get(
        '/api/v1/ai/conversations/$conversationId',
      );

      final now = DateTime.now();
      await _conversationDao.upsertConversation(
        AiConversationsCompanion.insert(
          id: conversationId,
          companyId: convData['company_id'] as String? ?? '',
          projectId: drift.Value(convData['project_id'] as String?),
          scopeId: drift.Value(convData['scope_id'] as String?),
          userId: convData['user_id'] as String? ?? '',
          convType: convType,
          status: const drift.Value('completed'),
          transcriptJson: drift.Value(
            jsonEncode(convData['messages'] ?? []),
          ),
          createdAt: now,
          updatedAt: now,
        ),
      );
    } catch (e) {
      // Non-fatal: local sync failure doesn't fail the completion
      debugPrint('[InterviewChatNotifier] _syncTranscriptToLocal error: $e');
    }
  }
}

/// Provider for the interview chat notifier, parameterized by scopeId.
///
/// Uses Riverpod 3 family pattern: factory (arg) => Notifier(arg).
/// Auto-disposed when the interview screen is popped.
final interviewChatProvider = NotifierProvider.autoDispose
    .family<InterviewChatNotifier, InterviewChatState, String>(
  (scopeId) => InterviewChatNotifier(scopeId),
);
